### ISSUE TITLE
Bug Fix for Next and Test Specs.

### ISSUE THREAD

**Issue by Emanao** [learn-co-curriculum/diy-json-serializer-lab#14]
CODE:
To prevent the anchor tag from opening the link(default behavior), I added the JQuery method preventDefault.
Returning false from jQuery event handlers is equivalent to calling both, e.preventDefault and e.stopPropagation. So it also works.
SPEC:
Line 15 from product_feature_spec commented.
I guess that the spec solution is: "expect(page).to have_content p2.name" or "expect(page).not_to have_content p1.name" instead of "expect(page).not_to have_content p2.name". 
It makes no sense that after clicking "Next Product" the expectations are: not to have the name of the next product.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
