### ISSUE TITLE
Test Suite not compatible with ES6

### ISSUE THREAD

**Issue by dj-sf** [learn-co-curriculum/diy-json-serializer-lab#6]
After debugging some issues, I realized that this and some other labs in this section have difficulties with the new ES6 syntax of JavaScript.  Most notably, the tests do not recognize variables declared with "let"... they only recognize those declared with "var".  This should be either corrected or a note should be made in the lab readme not to use "let".  The same should be done with other labs with the same testing setup as this one.

**Comment by d-d-d-dalia** [comment]
This also applies to using back ticks for interpolation. Instead of interpolating, just concatenate in this lab, as the back ticks in the interpolation seem to cause the Capybara::Poltergeist::Javascript error.

**Comment by micahshute** [comment]
Fetch also does not work
